name: Build Lisa Kernel With KSU-0.9.5 LXC
on:

  workflow_dispatch:

jobs:
  build:
    name: Build Kernel LMO KSU LXC
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup host environment
      run: |
        sudo apt update
        sudo apt install libc6-dev clang flex bison libssl-dev bc python3 python2 zip unzip git lld llvm
        mkdir -p $GITHUB_WORKSPACE/kernel_workspace

    - name: Download kernel source
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/LineageOS/android_kernel_xiaomi_sm8350.git --depth=1

    - name: Download Proton-clang
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android_kernel_xiaomi_sm8350
        git clone https://github.com/kdrag0n/proton-clang.git proton-clang --depth=1
        export PATH="$GITHUB_WORKSPACE/kernel_workspace/android_kernel_xiaomi_sm8350/proton-clang/bin:$PATH"

    - name: Integrate KernelSU
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android_kernel_xiaomi_sm8350
        rm -rf KernelSU/
        cp -pf $GITHUB_WORKSPACE/ksupatch.sh ksupatch.sh
        chmod +x ksupatch.sh
        ./ksupatch.sh
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5

    - name: Compiling Kernel
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android_kernel_xiaomi_sm8350
        mkdir utils
        cp -pf $GITHUB_WORKSPACE/utils/* ./utils/
        echo 'source "utils/Kconfig"' >> "Kconfig"
        chmod +x $GITHUB_WORKSPACE/kernel_workspace/android_kernel_xiaomi_sm8350/utils/runcpatch.sh
        if [ -f $GITHUB_WORKSPACE/kernel_workspace/android_kernel_xiaomi_sm8350/kernel/cgroup/cgroup.c ]; then
            sh $GITHUB_WORKSPACE/kernel_workspace/android_kernel_xiaomi_sm8350/utils/runcpatch.sh $GITHUB_WORKSPACE/kernel_workspace/android_kernel_xiaomi_sm8350/kernel/cgroup/cgroup.c
        fi
        if [ -f $GITHUB_WORKSPACE/kernel_workspace/android_kernel_xiaomi_sm8350/kernel/cgroup.c ]; then
            sh $GITHUB_WORKSPACE/kernel_workspace/android_kernel_xiaomi_sm8350/utils/runcpatch.sh $GITHUB_WORKSPACE/kernel_workspace/android_kernel_xiaomi_sm8350/kernel/cgroup.c
        fi
        if [ -f $GITHUB_WORKSPACE/kernel_workspace/android_kernel_xiaomi_sm8350/net/netfilter/xt_qtaguid.c ]; then
             patch -p0 < $GITHUB_WORKSPACE/kernel_workspace/android_kernel_xiaomi_sm8350/utils/xt_qtaguid.patch
        fi
        cp -pf $GITHUB_WORKSPACE/lindroid_GKI.config arch/arm64/configs/vendor/lindroid_GKI.config
        cp -pf $GITHUB_WORKSPACE/lmo.sh build.sh
        chmod +x build.sh
        ./build.sh
        filename=$(find . -name LineageOS* -printf '%f\n')
        echo $filename
        echo "FILENAME=$filename" >> $GITHUB_ENV

    - name: Uploading Kernel to artifact
      uses: actions/upload-artifact@v4
      with:
        name: LineageOS_KernelSU
        path: ${{ github.workspace }}/kernel_workspace/android_kernel_xiaomi_sm8350/${{ env.FILENAME }}